-- Create tables employees, customers, timeentries and total_hours
-- Insert 3 rows per table

CREATE TABLE employees (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consultant_name VARCHAR(200) NOT NULL
);

INSERT INTO employees (consultant_name) VALUES
('Alice Andersson'),
('Bob Svensson'),
('Charlie Nilsson'),
('David Karlsson'),
('Emma Johansson'),
('Filip Eriksson'),
('Greta Lindberg'),
('Henrik Larsson'),
('Ida Bergström'),
('Johan Gustafsson'),
('Karin Holm'),
('Lukas Persson'),
('Maria Ekström'),
('Niklas Lund'),
('Olivia Sjöberg'),
('Peter Nyberg'),
('Sara Dahl'),
('Tobias Åström');

CREATE TABLE customers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(200) NOT NULL
);

INSERT INTO customers (customer_name) VALUES
('Acme AB'),
('Globex AB'),
('Initech AB'),
('Nordic Solutions AB'),
('TechNova AB'),
('Blue Sky Consulting AB'),
('Digital Dynamics AB'),
('Future Systems AB'),
('Scandinavian Logistics AB'),
('Green Energy AB'),
('CloudWorks AB'),
('Smart Solutions AB'),
('NextGen Technologies AB'),
('Stockholm Design AB'),
('Data Insights AB'),
('Innovation Partners AB'),
('Arctic Ventures AB'),
('Secure Systems AB');


CREATE TABLE timeentries (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    consultant_id INT NOT NULL,
    customer_id INT NOT NULL,

    work_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,

    lunch_break INT NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_timeentries_consultant
        FOREIGN KEY (consultant_id)
        REFERENCES employees(id),

    CONSTRAINT fk_timeentries_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(id),

    CONSTRAINT valid_time_range
        CHECK (end_time > start_time),

    CONSTRAINT valid_lunch_break
        CHECK (lunch_break >= 0)
);

INSERT INTO timeentries (
    consultant_id,
    customer_id,
    work_date,
    start_time,
    end_time,
    lunch_break
) VALUES
(1, 1, '2026-08-24', '08:00', '17:00', 60),
(2, 1, '2026-08-24', '09:00', '17:00', 30),
(3, 2, '2026-08-24', '08:30', '16:30', 45),
(4, 4, '2026-08-24', '08:00', '17:00', 60),
(5, 5, '2026-08-24', '08:30', '17:00', 30),
(6, 6, '2026-08-24', '09:00', '18:00', 60),
(7, 7, '2026-08-25', '08:00', '16:30', 30),
(8, 8, '2026-08-25', '08:30', '17:00', 45),
(9, 9, '2026-08-25', '07:30', '16:30', 60),
(10, 10, '2026-08-25', '09:00', '17:00', 30),
(11, 11, '2026-08-26', '08:00', '17:00', 60),
(12, 12, '2026-08-26', '08:30', '16:30', 30),
(13, 13, '2026-08-26', '09:00', '17:30', 45),
(14, 14, '2026-08-26', '08:00', '16:00', 30),
(15, 15, '2026-08-27', '08:30', '17:00', 60),
(16, 16, '2026-08-27', '09:00', '18:00', 45),
(17, 17, '2026-08-27', '07:30', '16:00', 30),
(18, 18, '2026-08-27', '08:00', '17:00', 60);
